meta:
  engine: 4.1.0
units:
  kx: 19
  ky: 19
  px: kx+0.5
  py: ky+0.5
  drill_radius: 0.8
  mcu_spacing: 20 
  central_offset: mcu_spacing/2
points:
  zones:
    matrix:
      anchor:
        shift: [100, -175]
      key:
        padding: 1ky
        spread: 1kx
      columns:
        leftpinky:
          rows.thumb.skip: true
          key:
            column_net: P2
        leftring:
          rows.thumb.skip: true
          key:
            column_net: P3
        leftmiddle:
          rows.thumb.skip: true
          key:
            column_net: P4
        leftindex:
          key:
            column_net: P5
        leftinner:
          key:
            column_net: P6
        mcu:
          key:
            skip: true
            spread: mcu_spacing 
        rightinner:
          key:
            column_net: P7
        rightindex:
          key:
            column_net: P8
        rightmiddle:
          key:
            column_net: P9
          rows.thumb.skip: true
        rightring:
          key:
            column_net: P10
          rows.thumb.skip: true
        rightpinky:
          key:
            column_net: P16
          rows.thumb.skip: true
      rows:
        thumb:
          row_net: P14
        bottom:
          row_net: P15
        home:
          row_net: P18
        top:
          row_net: P19
outlines:
  raw:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_leftpinky_top
          shift: [-0.5px, 0.5py]
        - ref: matrix_rightpinky_top
          shift: [0.5px, 0.5py]
        - ref: matrix_rightpinky_bottom
          shift: [0.5px, -0.5py]
        - ref: matrix_rightindex_bottom
          shift: [0.5px, -0.5py]
        - ref: matrix_rightindex_thumb
          shift: [0.5px, -0.5py]
        - ref: matrix_leftindex_thumb
          shift: [-0.5px, -0.5py]
        - ref: matrix_leftindex_bottom
          shift: [-0.5px, -0.5py]
        - ref: matrix_leftpinky_bottom
          shift: [-0.5px, -0.5py]
  keys:
    - what: rectangle
      where: true
      bound: false
      size: [14, 14]
  pcb_cutout:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_leftinner_bottom
          shift: [0.5px, 0.65py]
        - ref: matrix_rightinner_bottom
          shift: [-0.5px, 0.65py]
        - ref: matrix_rightinner_bottom
          shift: [-0.5px, -10py]
        - ref: matrix_leftinner_bottom
          shift: [0.5px, -10py]
  plate_cutout:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_leftinner_bottom
          shift: [0.5px, 0.65py]
        - ref: matrix_rightinner_bottom
          shift: [-0.5px, 0.65py]
        - ref: matrix_rightinner_bottom
          shift: [-0.5px, 10py]
        - ref: matrix_leftinner_bottom
          shift: [0.5px, 10py]
  pcb:
    - name: raw
    - operation: subtract
      name: pcb_cutout
      fillet: 0.8
  plate:
    - name: raw
    - operation: subtract
      name: plate_cutout
    - operation: subtract
      name: keys
pcbs:
  board:
    template: kicad8
    outlines:
      main:
        outline: pcb
    footprints:
      keyswitches:
        where: true
        what: ceoloide/switch_choc_v1_v2
        params:
          include_keycap: true
          solder: false
          include_stabilizer_pad: false
          choc_v1_support: false
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: ceoloide/diode_tht_sod123
        where: true
        params:
          include_traces_vias: true
          reversible: true
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -0.28ky]
      mcu:
        what: ceoloide/mcu_supermini_nrf52840
        params:
          side: F
          show_silk_labels: false
        where:
          ref: matrix_leftinner_top
          shift: [0.5kx+central_offset,-0.5ky+2.7]
      reset:
        what: ceoloide/reset_switch_smd_side
        params:
          side: B
          include_bosses: true
        where:
          ref: matrix_leftinner_top
          shift: [0.5kx+central_offset+6.38,8]
      power:
        what: ceoloide/power_switch_smd_side
        params:
          side: B
        where:
          ref: matrix_leftinner_top
          shift: [0.5kx+central_offset-6.76,8.25]
          rotate: 90
      battery:
        what: ceoloide/battery_connector_molex_pico_ezmate_1x02
        params:
          side: B
        where:
          ref: matrix_leftinner_home
          shift: [0.5kx+central_offset,8]
 
